[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/despre"
  to = "/despre-noi"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200